### ISSUE TITLE
Create BPA cards at IAA Go

### ISSUE THREAD

**Issue by mgwalker** [18F/acq-trello-listener#1]
Given that a card on the Acq-intake is has “Agile BPA” in the title,
When I move it into the “IAA Go - Write 7600 (WIP Limit == 5)” List,
Then a card should be created on the BPA-Dashboard in the IAA list
And then the card title will be taken from the Intake card title.
And a new full board will be created and linked to the bpa and the intake trello card.
And a comment will be added to the Intake card that a new card was create in the bpa-dashboard

**Comment by mgwalker** [comment]
@lauraGgit - Is this correct, we need to create a whole new _board_ for each BPA order?

**Comment by lauraGgit** [comment]
@mgwalker Yes, the order needs a card on the bpa trello dashboard
 _and_ a board for the actual project management.

**Comment by mgwalker** [comment]
Cool, easy to do.  I'm curious if these links should be comments or if they should go in the description.  Putting them in the description keeps them near the top, whereas a comment can drop down the card over time.  Comments for now is good, though.  In practice, maybe the cards don't change often enough that the links will drop very far.

**Comment by lauraGgit** [comment]
For the other cards creator applications we've put the trello links in the
description.
